import React, { useState } from 'react';
import { useTaskStore } from '../../store/useTaskStore';
import {
  Sparkles,
  X,
  Send,
  CalendarCheck,
  Zap,
  Layers,
  Flame,
  BrainCircuit,
  CheckCircle,
} from 'lucide-react';
import { soundEngine } from '../../store/soundEffects';

export const AIAssistantModal: React.FC = () => {
  const {
    isAiModalOpen,
    setIsAiModalOpen,
    tasks,
    timetable,
    habits,
    addTask,
    addTimetableEvent,
    settings,
    showToast,
  } = useTaskStore();

  const [input, setInput] = useState('');
  const [messages, setMessages] = useState<
    { id: string; sender: 'ai' | 'user'; text: string; action?: { label: string; execute: () => void } }[]
  >([
    {
      id: 'msg_1',
      sender: 'ai',
      text: "Greetings, Commander. I am your TaskVerse Quantum AI Copilot. I've analyzed your schedule and noticed you have high-cognitive load tasks due today. How may I optimize your execution pipeline?",
    },
  ]);
  const [isTyping, setIsTyping] = useState(false);

  if (!isAiModalOpen) return null;

  const handleSend = (customPrompt?: string) => {
    const textToSend = customPrompt || input;
    if (!textToSend.trim()) return;

    if (settings.enableSoundEffects) soundEngine.playClick(0.15);

    const userMsgId = `user_${Date.now()}`;
    setMessages((prev) => [...prev, { id: userMsgId, sender: 'user', text: textToSend }]);
    setInput('');
    setIsTyping(true);

    setTimeout(() => {
      setIsTyping(false);
      if (settings.enableSoundEffects) soundEngine.playSuccess(0.2);

      let replyText = '';
      let replyAction: { label: string; execute: () => void } | undefined = undefined;

      const lower = textToSend.toLowerCase();

      if (lower.includes('timetable') || lower.includes('schedule') || lower.includes('optimize')) {
        replyText =
          "⚡ Timetable Optimization Complete: I detected that your evening lacks dedicated wind-down buffers. I've formulated a 60-minute Deep Synthesis session for 19:30 with zero overlapping conflicts.";
        replyAction = {
          label: 'Apply AI Schedule Slot to Timetable',
          execute: () => {
            addTimetableEvent({
              title: 'AI Synthesized Deep Work Session',
              category: 'Coding',
              dayOfWeek: 'Saturday',
              startTime: '19:30',
              endTime: '20:30',
              isRecurring: false,
              type: 'Deep Work',
              color: '#06b6d4',
            });
          },
        };
      } else if (lower.includes('break down') || lower.includes('subtask') || lower.includes('task')) {
        replyText =
          "🎯 Quantum Task Decomposition: I've broken down 'Autonomous Multi-Agent AI System' into 4 atomic 25-minute execution sprints.";
        replyAction = {
          label: 'Create Structured Task from AI Breakdown',
          execute: () => {
            addTask({
              title: 'Agent Memory Graph Ingestion Pipeline',
              description: 'AI Generated: Build Redis vector store retrieval hook for long-term multi-turn conversation caching.',
              priority: 'High',
              category: 'Coding',
              deadline: new Date().toISOString().split('T')[0],
              dueTime: '17:00',
              tags: ['AI/ML', 'AutoGenerated'],
              estimatedDuration: 45,
              status: 'Todo',
              subtasks: [
                { id: 'sb_ai_1', title: 'Initialize embedding pipeline', completed: false },
                { id: 'sb_ai_2', title: 'Test semantic distance threshold', completed: false },
              ],
            });
          },
        };
      } else if (lower.includes('motivation') || lower.includes('quote') || lower.includes('inspire')) {
        replyText =
          "🌟 Neuro-Affirmation: 'You do not rise to the level of your goals. You fall to the level of your systems.' — Your current streak of 14 days puts you in the top 2% of hyper-focused executors.";
      } else {
        replyText = `Understood. Analyzing parameters for "${textToSend}". I have cross-referenced your ${tasks.length} active tasks, ${timetable.length} timetable events, and ${habits.length} daily habits. Your focus velocity is operating at 94% peak efficiency today!`;
      }

      setMessages((prev) => [
        ...prev,
        {
          id: `ai_${Date.now()}`,
          sender: 'ai',
          text: replyText,
          action: replyAction,
        },
      ]);
    }, 800);
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-md animate-in fade-in duration-200"
      onClick={() => setIsAiModalOpen(false)}
    >
      <div
        className="relative w-full max-w-2xl h-[620px] rounded-3xl border border-cyan-500/30 bg-slate-950/90 backdrop-blur-2xl flex flex-col shadow-2xl shadow-cyan-950/50 overflow-hidden animate-in zoom-in-95 duration-200"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Holographic Glowing Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-white/10 bg-gradient-to-r from-cyan-950/40 via-slate-900 to-purple-950/40">
          <div className="flex items-center gap-3">
            <div className="relative flex items-center justify-center w-10 h-10 rounded-2xl bg-cyan-500/20 border border-cyan-500/40 text-cyan-300">
              <Sparkles className="w-5 h-5 animate-pulse" />
              <span className="absolute -bottom-0.5 -right-0.5 w-2.5 h-2.5 rounded-full bg-emerald-400 border-2 border-slate-950 animate-ping" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="font-extrabold text-sm text-white">TaskVerse AI Copilot</h3>
                <span className="px-2 py-0.5 rounded-full bg-cyan-500/20 text-cyan-300 text-[10px] font-mono font-bold">
                  Neural v4.5
                </span>
              </div>
              <p className="text-[11px] text-slate-400">Autonomous Schedule & Strategy Engine</p>
            </div>
          </div>

          <button
            onClick={() => setIsAiModalOpen(false)}
            className="p-2 rounded-xl text-slate-400 hover:text-white hover:bg-white/10 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Quick Suggestion Chips */}
        <div className="flex items-center gap-2 px-6 py-2.5 bg-slate-900/40 border-b border-white/5 overflow-x-auto no-scrollbar">
          {[
            { label: '⚡ Optimize Timetable', prompt: 'Optimize my timetable and resolve schedule conflicts for today' },
            { label: '🎯 Break Down Task', prompt: 'Break down my critical coding task into subtasks' },
            { label: '🔥 Neuro Motivation', prompt: 'Give me a powerful stoic neuro-productivity boost' },
            { label: '📊 Velocity Diagnosis', prompt: 'Analyze my weekly completion metrics and diagnose bottlenecks' },
          ].map((chip, idx) => (
            <button
              key={idx}
              onClick={() => handleSend(chip.prompt)}
              className="shrink-0 px-3 py-1 rounded-full bg-white/5 hover:bg-cyan-500/20 border border-white/10 hover:border-cyan-500/30 text-[11px] text-slate-300 hover:text-cyan-300 font-medium transition-all cursor-pointer"
            >
              {chip.label}
            </button>
          ))}
        </div>

        {/* Chat Stream Messages */}
        <div className="flex-1 overflow-y-auto p-6 space-y-4">
          {messages.map((m) => (
            <div
              key={m.id}
              className={`flex items-start gap-3 ${m.sender === 'user' ? 'flex-row-reverse' : ''}`}
            >
              {m.sender === 'ai' && (
                <div className="w-8 h-8 rounded-xl bg-cyan-500/20 border border-cyan-500/40 flex items-center justify-center text-cyan-300 shrink-0 mt-0.5">
                  <BrainCircuit className="w-4 h-4" />
                </div>
              )}
              <div
                className={`max-w-[80%] p-4 rounded-2xl text-xs leading-relaxed ${
                  m.sender === 'user'
                    ? 'bg-gradient-to-r from-cyan-600 to-blue-600 text-white rounded-tr-sm shadow-md shadow-cyan-950/50'
                    : 'bg-slate-900/80 border border-white/10 text-slate-200 rounded-tl-sm shadow-xl'
                }`}
              >
                <p className="whitespace-pre-line">{m.text}</p>

                {m.action && (
                  <div className="mt-3 pt-3 border-t border-white/10">
                    <button
                      onClick={() => {
                        m.action?.execute();
                        if (settings.enableSoundEffects) soundEngine.playSuccess(0.2);
                        showToast('AI Recommendation action executed!', 'success');
                      }}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-cyan-500/20 hover:bg-cyan-500/30 border border-cyan-500/40 text-cyan-300 text-[11px] font-bold transition-all cursor-pointer hover:scale-105"
                    >
                      <CheckCircle className="w-3.5 h-3.5" />
                      <span>{m.action.label}</span>
                    </button>
                  </div>
                )}
              </div>
            </div>
          ))}

          {isTyping && (
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-xl bg-cyan-500/20 border border-cyan-500/40 flex items-center justify-center text-cyan-300 shrink-0">
                <BrainCircuit className="w-4 h-4 animate-spin" />
              </div>
              <div className="px-4 py-3 rounded-2xl bg-slate-900/80 border border-white/10 text-xs text-slate-400 flex items-center gap-1.5">
                <span className="w-1.5 h-1.5 rounded-full bg-cyan-400 animate-bounce" style={{ animationDelay: '0ms' }} />
                <span className="w-1.5 h-1.5 rounded-full bg-cyan-400 animate-bounce" style={{ animationDelay: '150ms' }} />
                <span className="w-1.5 h-1.5 rounded-full bg-cyan-400 animate-bounce" style={{ animationDelay: '300ms' }} />
              </div>
            </div>
          )}
        </div>

        {/* Input Bar */}
        <div className="p-4 border-t border-white/10 bg-slate-950">
          <form
            onSubmit={(e) => {
              e.preventDefault();
              handleSend();
            }}
            className="flex items-center gap-2"
          >
            <input
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Ask AI Copilot to schedule, break down goals, or diagnose performance..."
              className="flex-1 px-4 py-2.5 rounded-xl bg-white/5 border border-white/10 focus:border-cyan-400 focus:ring-1 focus:ring-cyan-400 text-xs text-white placeholder:text-slate-500 focus:outline-none"
            />
            <button
              type="submit"
              disabled={!input.trim()}
              className="p-2.5 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-slate-950 font-bold transition-all cursor-pointer disabled:opacity-40"
            >
              <Send className="w-4 h-4" />
            </button>
          </form>
        </div>
      </div>
    </div>
  );
};
